# Generated by Django 2.0.2 on 2018-03-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
