# Generated by Django 2.0.2 on 2018-03-31 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorage', '0002_user_password_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '部门'},
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='restorage.Department'),
        ),
    ]
